apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: lb-policy-arp
spec:
  serviceSelector:
    matchLabels:
      color: red
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  interfaces:
  - eth0
  externalIPs: true
  loadBalancerIPs: true
