apiVersion: apps/v1
kind: Deployment
metadata:
  name: cillium-lb-test3
spec:
  selector:
    matchLabels:
      app: nginx
      color: red
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
        color: red
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cillium-lb-test3
  labels:
    app: nginx
    color: red
  #annotations:
  #  "io.cilium/lb-ipam-ips": "10.0.1.49"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector: 
    app: nginx
    color: red
