apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: lb-arp-policy
spec:
  serviceSelector:
    matchLabels:
      color: red
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  interfaces:
  - eth0
  externalIPs: true
  loadBalancerIPs: true
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "red-pool"
  namespace: cilium-system
spec:
  cidrs:
  - cidr: "10.0.1.24/29"
  serviceSelector:
    matchLabels:
      color: red
