cilium:
  ipam:
    operator:
      clusterPoolIPv4PodCIDRList: 10.92.0.0/16
  kubeProxyReplacement: strict
  k8sServiceHost: 10.0.1.70
  k8sServicePort: 6443
  l2announcements:
    enabled: true
    leaseDuration: 3s
    leaseRenewDeadline: 1s
    leaseRetryPeriod: 200ms
  devices: eth+
  externalIPs:
    enabled: true
  k8sClientRateLimit.qps: 30
  k8sClientRateLimit.burst: 40
  hubble:
    relay:
      enabled: true
    ui:
      enabled: true
    peerService:
      clusterDomain: service-az1.local
    tls:
      enabled: false
